Repository GreenmaskIO/greenmask, pull requests merged in 2024-02, with the labels that each got.

#5 Json transformer and connection string fixes
  internal/db/postgres/pgdump/pgdump.go
  internal/db/postgres/pgrestore/pgrestore.go
  internal/db/postgres/transformers/json.go
  internal/db/postgres/transformers/json_test.go
Labels: bug

#9 CI/CD Change. Pack binaries, Licence and summaries into one archive file
  .github/workflows/ci.yml
Labels: enhancement

#12 Playground fixes
  docker-compose.yml
  playground/cleanup.sh
Labels: bug

#11 New Hash transformer implementation and validation warning fixes
  internal/db/postgres/transformers/cmd.go
  internal/db/postgres/transformers/hash.go
  internal/db/postgres/transformers/hash_test.go
  pkg/toolkit/parameter.go
Labels: bug, enhancement

#10 Command interface improvements
  cmd/greenmask/cmd/dump/dump.go
  cmd/greenmask/cmd/list_dumps/list_dumps.go
  cmd/greenmask/cmd/list_transformers/list_transformers.go
  cmd/greenmask/cmd/restore/restore.go
  cmd/greenmask/cmd/root.go
  cmd/greenmask/cmd/show_transformer/show_transformer.go
  internal/db/postgres/transformers/cmd.go
  internal/db/postgres/transformers/real_address.go
  pkg/toolkit/parameter.go
  tests/integration/toc/backward_compatibility_test.go
Labels: bug, enhancement

#13 Fix: fixed credit_card variable
  internal/db/postgres/transformers/masking.go
  internal/db/postgres/transformers/utils/template/functions.go
Labels: bug
