Repository GreenmaskIO/greenmask, pull requests merged in 2024-05, with the labels that each got.

#103 fix: fixed large object dumper panic caused by wrong function enclosure
  internal/db/postgres/dumpers/large_object.go
Labels: bug

#98 Feat: RandomPerson transformer
  docs/built_in_transformers/standard_transformers/index.md
  docs/built_in_transformers/standard_transformers/random_first_name.md
  docs/built_in_transformers/standard_transformers/random_first_name_female.md
  docs/built_in_transformers/standard_transformers/random_first_name_male.md
  docs/built_in_transformers/standard_transformers/random_last_name.md
  docs/built_in_transformers/standard_transformers/random_name.md
  docs/built_in_transformers/standard_transformers/random_person.md
  docs/built_in_transformers/standard_transformers/random_title_female.md
  docs/built_in_transformers/standard_transformers/random_title_male.md
  docs/release_notes/greenmask_0_1_1.md
  internal/db/postgres/transformers/data.go
  internal/db/postgres/transformers/random_faker.go
  internal/db/postgres/transformers/random_person.go
  internal/db/postgres/transformers/random_person_test.go
  internal/generators/transformers/random_person.go
  internal/generators/transformers/random_person_test.go
  mkdocs.yml
Labels: feature

#112 fix: Fixes in NoiseData transformer
  internal/db/postgres/transformers/noise_date.go
  internal/db/postgres/transformers/random_date.go
Labels: bug

#119 fix: Fixed NoiseNumeric and RandomNumeric limiters
  internal/db/postgres/transformers/noise_numeric.go
  internal/db/postgres/transformers/random_numeric.go
  internal/generators/transformers/noise_numeric.go
  internal/generators/transformers/random_numeric.go
  internal/generators/transformers/random_numeric_test.go
Labels: bug

#120 fix: Added column size calculation based on type or column size
  internal/db/postgres/transformers/noise_float.go
  internal/db/postgres/transformers/noise_int.go
  internal/db/postgres/transformers/random_float.go
  internal/db/postgres/transformers/random_int.go
  internal/db/postgres/transformers/tesing_helpers_test.go
  pkg/toolkit/column.go
Labels: bug

#121 fix: transformers precision parameter to decimal
  docs/commands.md
  internal/db/postgres/transformers/noise_float.go
  internal/db/postgres/transformers/noise_float_test.go
  internal/db/postgres/transformers/noise_numeric.go
  internal/db/postgres/transformers/noise_numeric_test.go
  internal/db/postgres/transformers/random_float.go
  internal/db/postgres/transformers/random_float_test.go
  internal/db/postgres/transformers/random_numeric.go
  pkg/toolkit/template_functions.go
  pkg/toolkit/template_functions_test.go
Labels: enhancement

#122 Random mac address
  docs/built_in_transformers/standard_transformers/index.md
  docs/built_in_transformers/standard_transformers/random_mac.md
  internal/db/postgres/transformers/random_mac.go
  internal/db/postgres/transformers/random_mac_test.go
  internal/generators/transformers/random_mac.go
  internal/generators/transformers/random_mac_test.go
  pkg/toolkit/parameter_definition.go
  pkg/toolkit/static_parameter.go
Labels: feature

#124 doc: Fixed overridden_column_type logic
  internal/db/postgres/context/table.go
  pkg/toolkit/column.go
  pkg/toolkit/static_parameter.go
Labels: enhancement

#125 fix: Revised RandomMac transformer
  internal/db/postgres/transformers/random_mac.go
  internal/db/postgres/transformers/random_mac_test.go
  internal/db/postgres/transformers/tesing_helpers_test.go
  internal/generators/transformers/random_mac.go
  internal/generators/transformers/random_mac_test.go
Labels: enhancement

#126 Fix/units and allowed types
  internal/db/postgres/transformers/email.go
  internal/db/postgres/transformers/random_faker.go
  internal/db/postgres/transformers/random_ip.go
  internal/db/postgres/transformers/random_ip_test.go
  internal/db/postgres/transformers/random_mac.go
  internal/db/postgres/transformers/random_mac_test.go
  internal/db/postgres/transformers/random_unix_timestamp.go
  pkg/toolkit/tesing_helpers.go
Labels: enhancement

#127 feat: Introduced static parameters value template
  docs/built_in_transformers/parameters_templating.md
  internal/db/postgres/transformers/dict.go
  internal/db/postgres/transformers/noise_date.go
  internal/db/postgres/transformers/noise_float.go
  internal/db/postgres/transformers/noise_int.go
  internal/db/postgres/transformers/noise_numeric.go
  internal/db/postgres/transformers/random_date.go
  internal/db/postgres/transformers/random_float.go
  internal/db/postgres/transformers/random_int.go
  internal/db/postgres/transformers/random_ip.go
  internal/db/postgres/transformers/random_mac.go
  internal/db/postgres/transformers/random_numeric.go
  internal/db/postgres/transformers/random_person.go
  internal/db/postgres/transformers/random_string.go
  internal/db/postgres/transformers/random_unix_timestamp.go
  mkdocs.yml
  pkg/toolkit/static_parameter.go
Labels: feature

#128 fix: Fixed documentation latest tag exclusion for beta
  .github/workflows/ci.yml
  docs/overrides/main.html
Labels: bug
